sudo: required
services:
- docker
script:
- sbt ++$TRAVIS_SCALA_VERSION it:test

language: scala
scala:
- 2.11.8
jdk:
- openjdk8

before_deploy:
# Record minimal build information via the Git user ident
- git config --global user.name "$USER"
- git config --global user.email "$TRAVIS_BUILD_NUMBER@$TRAVIS_COMMIT"
# Decrypt the secret deploy key using instructions from `travis encrypt-file`
- openssl aes-256-cbc -K $encrypted_337ba72fd12b_key -iv $encrypted_337ba72fd12b_iv -in project/travis-deploy-key.enc -out project/travis-deploy-key -d
- chmod 600 project/travis-deploy-key
# Start ssh-agent in the background and load the deploy key
- eval "$(ssh-agent -s)"
- ssh-add project/travis-deploy-key

deploy:
  provider: script
  script: sbt ghpagesPushSite
  skip_cleanup: true
  on:
    condition: $TRAVIS_PULL_REQUEST = false
